name = "craftoria-2"
author = "TeamAOE"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76f62c874c6b99537a9f73819823e62c9e45f1085162a80e8e0a405d3eac6669"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"
