name = "craftoria-2"
author = "TeamAOE"
version = "0.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2398d5a346d8aeb5e617a5ef234214e1529f35210f7e7618b197fc5336a810a"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"
